// src/verses.js
// All verse text is King James Version (public domain — free to ship).
// The "w" field is the personality reflection shown above each verse (original writing).
// 30 verses per voice → a full month of daily rotation before any repeat.

export const ACCENT_DEFAULT = '#e3a155';
export const GLOW_DEFAULT = 'rgba(227,161,85,.5)';

export const MODES = {
  shepherd: {
    name: 'The Shepherd',
    glyph: '🕯️',
    color: '#e3a155',
    glow: 'rgba(227,161,85,.5)',
    blurb: 'You were sought on purpose. Gentle reminders that you are not a number — you are the one.',
    verses: [
      { t: 'What man of you, having an hundred sheep, if he lose one of them, doth not leave the ninety and nine, and go after that which is lost, until he find it?', r: 'Luke 15:4',
        w: "You imagine being left behind. Read it again — you're the one He goes after." },
      { t: 'Joy shall be in heaven over one sinner that repenteth, more than over ninety and nine just persons.', r: 'Luke 15:7',
        w: "Heaven isn't disappointed in you. Heaven is throwing a party the day you turn around." },
      { t: 'But when he was yet a great way off, his father saw him, and had compassion, and ran, and fell on his neck, and kissed him.', r: 'Luke 15:20',
        w: "He saw you while you were still far off. He didn't wait for you to arrive — He ran." },
      { t: 'For the Son of man is come to seek and to save that which was lost.', r: 'Luke 19:10',
        w: "Being lost isn't disqualifying. It's the exact thing He came looking for." },
      { t: 'I will seek that which was lost, and bring again that which was driven away, and will bind up that which was broken.', r: 'Ezekiel 34:16',
        w: 'Not just found — bound up, healed, brought home. He finishes what He starts.' },
      { t: 'Fear not: for I have redeemed thee, I have called thee by thy name; thou art mine.', r: 'Isaiah 43:1',
        w: "He knows your name. Not the crowd's name — yours." },
      { t: 'The LORD is my shepherd; I shall not want.', r: 'Psalm 23:1',
        w: "Six words. If He's the one leading, lack isn't the end of your story." },
      { t: 'I am the good shepherd: the good shepherd giveth his life for the sheep.', r: 'John 10:11',
        w: "He didn't hire someone to come for you. He came Himself, and paid the whole price." },
      { t: 'My sheep hear my voice, and I know them, and they follow me.', r: 'John 10:27',
        w: "You worry you can't recognize His voice. He already recognizes yours." },
      { t: 'And I give unto them eternal life; and they shall never perish, neither shall any man pluck them out of my hand.', r: 'John 10:28',
        w: "You're not held by your grip on Him. You're held by His grip on you." },
      { t: 'He shall feed his flock like a shepherd: he shall gather the lambs with his arm, and carry them in his bosom.', r: 'Isaiah 40:11',
        w: "The weakest lamb doesn't get left to keep up. It gets carried." },
      { t: 'It is he that hath made us, and not we ourselves; we are his people, and the sheep of his pasture.', r: 'Psalm 100:3',
        w: "You belong to Someone. That's settled before you do a single thing right." },
      { t: 'Can a woman forget her sucking child, that she should not have compassion on the son of her womb? yea, they may forget, yet will I not forget thee.', r: 'Isaiah 49:15',
        w: "Even the most unforgettable love a human knows could fail. His can't." },
      { t: 'Behold, I have graven thee upon the palms of my hands.', r: 'Isaiah 49:16',
        w: "You're not a passing thought. You're carved where He can't look without seeing you." },
      { t: 'Yea, I have loved thee with an everlasting love: therefore with lovingkindness have I drawn thee.', r: 'Jeremiah 31:3',
        w: "His love didn't start when you got it together. It has no start. It just is." },
      { t: 'The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.', r: 'Zephaniah 3:17',
        w: "Picture God singing over you. That's not poetry — that's the verse." },
      { t: 'And when he hath found it, he layeth it on his shoulders, rejoicing.', r: 'Luke 15:5',
        w: "He doesn't drag the found sheep home scolding it. He carries it, glad." },
      { t: 'Rejoice with me; for I have found my sheep which was lost.', r: 'Luke 15:6',
        w: "Your coming home isn't a quiet relief to Him. It's something He calls the neighbors over for." },
      { t: 'For this my son was dead, and is alive again; he was lost, and is found.', r: 'Luke 15:24',
        w: "The far country doesn't get the last word. 'Found' does." },
      { t: 'For I am persuaded, that neither death, nor life, nor things present, nor things to come, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.', r: 'Romans 8:38-39',
        w: "Make the list of everything that could cut you off. Every item is already on the 'cannot' side." },
      { t: 'Him that cometh to me I will in no wise cast out.', r: 'John 6:37',
        w: "No fine print. No 'unless.' If you come, you are not turned away." },
      { t: 'Whither shall I go from thy spirit? or whither shall I flee from thy presence?', r: 'Psalm 139:7',
        w: "Even your wandering ran out of places He isn't. You never left His reach." },
      { t: 'If I take the wings of the morning, and dwell in the uttermost parts of the sea; even there shall thy hand lead me, and thy right hand shall hold me.', r: 'Psalm 139:9-10',
        w: "Go as far as you can imagine going. His hand is already there, waiting to hold yours." },
      { t: 'I will never leave thee, nor forsake thee.', r: 'Hebrews 13:5',
        w: "Read it slowly. There is no version of tomorrow where He walks out on you." },
      { t: 'Doth he not leave the ninety and nine, and goeth into the mountains, and seeketh that which is gone astray?', r: 'Matthew 18:12',
        w: "He goes into the mountains for one. The hard, cold, out-of-the-way places — for you." },
      { t: 'For ye were as sheep going astray; but are now returned unto the Shepherd and Bishop of your souls.', r: '1 Peter 2:25',
        w: "Astray isn't your address anymore. 'Returned' is." },
      { t: 'All we like sheep have gone astray; we have turned every one to his own way; and the LORD hath laid on him the iniquity of us all.', r: 'Isaiah 53:6',
        w: "You're not the only one who wandered. And the weight you carry was already laid on Him." },
      { t: 'They looked unto him, and were lightened: and their faces were not ashamed.', r: 'Psalm 34:5',
        w: "Stop staring at the mess and look up. Shame doesn't survive His face." },
      { t: 'I am the good shepherd, and know my sheep, and am known of mine.', r: 'John 10:14',
        w: "He doesn't know about you. He knows you — and wants to be known back." },
      { t: 'The LORD is nigh unto all them that call upon him, to all that call upon him in truth.', r: 'Psalm 145:18',
        w: "Not 'nigh to the impressive.' Nigh to all who call. That includes the version of you reading this." },
    ],
  },
  comforter: {
    name: 'The Comforter',
    glyph: '🤍',
    color: '#9cb8e0',
    glow: 'rgba(156,184,224,.45)',
    blurb: 'For the heavy days. A soft place to land when getting up feels like too much.',
    verses: [
      { t: 'The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.', r: 'Psalm 34:18',
        w: "He doesn't keep His distance from your lowest day. That's exactly where He draws near." },
      { t: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.', r: 'Matthew 11:28',
        w: "You don't have to fix yourself first. Bring the weight as it is. Rest is the invitation." },
      { t: 'He healeth the broken in heart, and bindeth up their wounds.', r: 'Psalm 147:3',
        w: 'The same hands that named the stars are gentle enough for your wounds.' },
      { t: 'Why art thou cast down, O my soul? hope thou in God: for I shall yet praise him.', r: 'Psalm 42:11',
        w: "Even the psalmist had to talk to his own heavy heart. You're in good company. The word is: yet." },
      { t: 'Weeping may endure for a night, but joy cometh in the morning.', r: 'Psalm 30:5',
        w: "The night is real. So is the morning. Don't let the dark convince you it's permanent." },
      { t: 'His compassions fail not. They are new every morning: great is thy faithfulness.', r: 'Lamentations 3:22-23',
        w: "Yesterday's mercy ran out — and there's a fresh batch waiting for you today." },
      { t: 'Blessed are they that mourn: for they shall be comforted.', r: 'Matthew 5:4',
        w: "Grief isn't a detour from blessing. He ties the comfort directly to the mourning." },
      { t: 'Blessed be God, even the Father of mercies, and the God of all comfort; who comforteth us in all our tribulation.', r: '2 Corinthians 1:3-4',
        w: "Not the God of some comfort, for some troubles. All comfort. All tribulation. No exceptions for yours." },
      { t: 'Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me.', r: 'Psalm 23:4',
        w: "He didn't promise you'd skip the valley. He promised you wouldn't walk it alone." },
      { t: 'God is our refuge and strength, a very present help in trouble.', r: 'Psalm 46:1',
        w: "Not a distant help you have to reach. A very present one, already in the room." },
      { t: 'Cast thy burden upon the LORD, and he shall sustain thee.', r: 'Psalm 55:22',
        w: "You weren't built to carry this. Set it down where it was always meant to go." },
      { t: 'Casting all your care upon him; for he careth for you.', r: '1 Peter 5:7',
        w: "All of it. The big fears and the small 3am ones. He actually cares — that's the reason." },
      { t: 'Peace I leave with you, my peace I give unto you. Let not your heart be troubled, neither let it be afraid.', r: 'John 14:27',
        w: "The world hands out a fragile peace. His is a different kind — and it's given, not earned." },
      { t: 'Let not your heart be troubled: ye believe in God, believe also in me.', r: 'John 14:1',
        w: "When your heart is loud, He doesn't shame the fear. He gives it somewhere to go." },
      { t: 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee.', r: 'Isaiah 41:10',
        w: "Count the promises in one breath: with you, your God, strengthen, help. You are not facing it on empty." },
      { t: 'The righteous cry, and the LORD heareth, and delivereth them out of all their troubles.', r: 'Psalm 34:17',
        w: "Your cry isn't lost in the noise. It's heard — and heard ones get answered." },
      { t: 'I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD.', r: 'Psalm 121:1-2',
        w: "When you don't know where to look, look up. Your help has an address, and it's Him." },
      { t: 'He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.', r: 'Psalm 91:1',
        w: "There's a quiet place that storms don't reach. You're invited to live there, not just visit." },
      { t: 'Take my yoke upon you, and learn of me; and ye shall find rest unto your souls.', r: 'Matthew 11:29',
        w: "His way isn't another weight to carry. It's the one that finally lets your soul exhale." },
      { t: 'And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying.', r: 'Revelation 21:4',
        w: "Tears get a final chapter, and He writes it Himself. This isn't how the story ends." },
      { t: 'When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee.', r: 'Isaiah 43:2',
        w: "Through, not around. The water rises — and it still doesn't get to pull you under." },
      { t: 'Put thou my tears into thy bottle: are they not in thy book?', r: 'Psalm 56:8',
        w: "Not one tear you've cried was wasted or unseen. He kept every one." },
      { t: 'My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever.', r: 'Psalm 73:26',
        w: "On the day you run completely out, He's still there — being the strength you don't have." },
      { t: 'Though I walk in the midst of trouble, thou wilt revive me.', r: 'Psalm 138:7',
        w: "In the middle of it — not after it's over — He revives. Help doesn't wait for the storm to pass." },
      { t: 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', r: 'Nahum 1:7',
        w: "On the worst day, He's not just good in theory. He's a place to hide that holds." },
      { t: 'The LORD upholdeth all that fall, and raiseth up all those that be bowed down.', r: 'Psalm 145:14',
        w: "If you're bowed down today, you're exactly who this verse names. He's the lifting kind." },
      { t: 'He hath sent me to bind up the brokenhearted, to proclaim liberty to the captives.', r: 'Isaiah 61:1',
        w: "Your broken heart isn't an inconvenience to His mission. It is the mission." },
      { t: 'To give unto them beauty for ashes, the oil of joy for mourning, the garment of praise for the spirit of heaviness.', r: 'Isaiah 61:3',
        w: "He doesn't just clear the ashes. He trades them — beauty for the very thing that burned." },
      { t: 'The LORD also will be a refuge for the oppressed, a refuge in times of trouble.', r: 'Psalm 9:9',
        w: "When everything feels like too much, there's a door marked refuge. It's Him, and it's open." },
      { t: 'And ye now therefore have sorrow: but I will see you again, and your heart shall rejoice, and your joy no man taketh from you.', r: 'John 16:22',
        w: "The sorrow is for now. The joy coming is the kind nobody gets to take back." },
    ],
  },
  fire: {
    name: 'The Fire',
    glyph: '🔥',
    color: '#ef7d3a',
    glow: 'rgba(239,125,58,.5)',
    blurb: 'When you need to get up. Bold, loud, get-off-the-floor energy for the comeback.',
    verses: [
      { t: 'They that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary.', r: 'Isaiah 40:31',
        w: "You're not running on your own tank anymore. Renewed strength is on the table. Get up." },
      { t: 'Behold, I will do a new thing; now it shall spring forth. I will even make a way in the wilderness, and rivers in the desert.', r: 'Isaiah 43:19',
        w: "That dry season you're in? He specializes in putting rivers exactly where there's no water." },
      { t: 'I can do all things through Christ which strengtheneth me.', r: 'Philippians 4:13',
        w: 'Not on a good day. Not when you feel it. All things — borrowed strength, not your own.' },
      { t: 'Be strong and of a good courage; be not afraid: for the LORD thy God is with thee whithersoever thou goest.', r: 'Joshua 1:9',
        w: "That's not a suggestion — it's a command, backed by a promise. Move." },
      { t: 'If God be for us, who can be against us?', r: 'Romans 8:31',
        w: 'Count the room. The only opinion that outweighs the rest is already on your side.' },
      { t: 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', r: '2 Timothy 1:7',
        w: 'That fear talking you out of it? Not from Him. Check the return address.' },
      { t: 'But my God shall supply all your need according to his riches in glory by Christ Jesus.', r: 'Philippians 4:19',
        w: "Not according to your bank account — according to His riches. Different math entirely." },
      { t: 'For I the LORD thy God will hold thy right hand, saying unto thee, Fear not; I will help thee.', r: 'Isaiah 41:13',
        w: "You're not walking in swinging blind. The God of everything has your right hand. Throw the punch." },
      { t: 'The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?', r: 'Psalm 27:1',
        w: "Ask the question out loud: whom shall I fear? With Him as your strength, the honest answer is nobody." },
      { t: 'But thanks be to God, which giveth us the victory through our Lord Jesus Christ.', r: '1 Corinthians 15:57',
        w: "The victory isn't something you're scraping for. It's something He gives. Walk in already-won." },
      { t: 'Nay, in all these things we are more than conquerors through him that loved us.', r: 'Romans 8:37',
        w: "Not barely surviving. More than conquerors. Quit negotiating for less than the verse says." },
      { t: 'For by thee I have run through a troop; and by my God have I leaped over a wall.', r: 'Psalm 18:29',
        w: "Troops and walls — and he's still moving. With God, the obstacle isn't the end of the road." },
      { t: 'For thou hast girded me with strength unto the battle.', r: 'Psalm 18:39',
        w: "He doesn't drop you into the fight unarmed. The strength is issued before the battle." },
      { t: 'No weapon that is formed against thee shall prosper.', r: 'Isaiah 54:17',
        w: "Things will get formed against you. Forming isn't prospering. Let them try." },
      { t: 'Only be thou strong and very courageous, that thou mayest observe to do according to all the law.', r: 'Joshua 1:7',
        w: "Not a little brave. Very courageous. He sets the bar high because He's the one holding you to it." },
      { t: 'The LORD shall fight for you, and ye shall hold your peace.', r: 'Exodus 14:14',
        w: "Some battles you win by going quiet and letting Him swing. Stop white-knuckling it." },
      { t: 'The joy of the LORD is your strength.', r: 'Nehemiah 8:10',
        w: "Joy isn't the reward for being strong. Joy is where the strength comes from. Tap in." },
      { t: 'The LORD God is my strength, and he will make my feet like hinds’ feet, and he will make me to walk upon mine high places.', r: 'Habakkuk 3:19',
        w: "The same ground that tripped you, He'll turn into the high place you stand on. Climb." },
      { t: 'God is in the midst of her; she shall not be moved: God shall help her, and that right early.', r: 'Psalm 46:5',
        w: "Help isn't running late. 'Right early' — He shows up before you'd even given up." },
      { t: 'Be not afraid nor dismayed by reason of this great multitude; for the battle is not yours, but God’s.', r: '2 Chronicles 20:15',
        w: "Outnumbered? Good. It was never your fight to win on your own anyway. It's His." },
      { t: 'When I fall, I shall arise; when I sit in darkness, the LORD shall be a light unto me.', r: 'Micah 7:8',
        w: "Say it to whatever knocked you down: when I fall, I shall arise. The fall isn't the verdict." },
      { t: 'In the day when I cried thou answeredst me, and strengthenedst me with strength in my soul.', r: 'Psalm 138:3',
        w: "The cry and the strength came the same day. Reach out — backup is faster than you think." },
      { t: 'He giveth power to the faint; and to them that have no might he increaseth strength.', r: 'Isaiah 40:29',
        w: "Empty is the prerequisite, not the disqualifier. To the ones with nothing left, He gives more." },
      { t: 'Finally, my brethren, be strong in the Lord, and in the power of his might.', r: 'Ephesians 6:10',
        w: "Not in the power of your willpower. His might. The source matters — and yours is unlimited." },
      { t: 'Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.', r: 'Psalm 31:24',
        w: "Courage first, strength follows. Make the move while it's still scary; He meets you in the motion." },
      { t: 'For the LORD your God is he that goeth with you, to fight for you against your enemies, to save you.', r: 'Deuteronomy 20:4',
        w: "He doesn't send you ahead and watch. He goes with you, and He fights to win." },
      { t: 'Arise, shine; for thy light is come, and the glory of the LORD is risen upon thee.', r: 'Isaiah 60:1',
        w: "The command and the reason in one breath: arise — because the light already came. Get up into it." },
      { t: 'Thou hast turned for me my mourning into dancing.', r: 'Psalm 30:11',
        w: "Same heart, new song. He's done turning mourning into dancing before, and yours is next." },
      { t: 'Greater is he that is in you, than he that is in the world.', r: '1 John 4:4',
        w: "Whatever's in front of you, do the comparison. What's in you is bigger. Act like it." },
      { t: 'Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ.', r: 'Philippians 1:6',
        w: "You're not a half-finished project He lost interest in. He finishes what He starts — including you." },
    ],
  },
  real: {
    name: 'The Real One',
    glyph: '⚡',
    color: '#d8c08a',
    glow: 'rgba(216,192,138,.42)',
    blurb: "Straight talk, no fluff. Tough love for the wilderness that's actually building you.",
    verses: [
      { t: 'For a just man falleth seven times, and riseth up again.', r: 'Proverbs 24:16',
        w: "Falling isn't the headline. The number that defines you is the getting-up count." },
      { t: 'Let us not be weary in well doing: for in due season we shall reap, if we faint not.', r: 'Galatians 6:9',
        w: "The harvest is late, not cancelled. Don't quit one season before it shows up." },
      { t: 'Thou shalt remember all the way which the LORD thy God led thee these forty years in the wilderness, to humble thee, and to prove thee.', r: 'Deuteronomy 8:2',
        w: "The desert wasn't a detour. It was the training. Stop asking to skip the part that's making you." },
      { t: 'Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life.', r: 'James 1:12',
        w: "Nobody's handing out crowns for comfort. The trial you're hating is the qualifier." },
      { t: 'Tribulation worketh patience; and patience, experience; and experience, hope.', r: 'Romans 5:3-4',
        w: "There's an actual order to this. The pressure isn't random — it's manufacturing something." },
      { t: 'In the world ye shall have tribulation: but be of good cheer; I have overcome the world.', r: 'John 16:33',
        w: "He told you it'd be hard so the hard wouldn't shake you. It's not a surprise. It's not the end." },
      { t: 'My brethren, count it all joy when ye fall into divers temptations; knowing this, that the trying of your faith worketh patience.', r: 'James 1:2-3',
        w: "Count it joy — not because it feels good, but because you know what it's building." },
      { t: 'But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.', r: 'James 1:4',
        w: "Stop rushing the process. Cutting it short just leaves you missing the part you needed." },
      { t: 'Now no chastening for the present seemeth to be joyous, but grievous: nevertheless afterward it yieldeth the peaceable fruit of righteousness.', r: 'Hebrews 12:11',
        w: "Of course it doesn't feel good now. 'Afterward' is the word doing the work. Stay for afterward." },
      { t: 'Let us run with patience the race that is set before us.', r: 'Hebrews 12:1',
        w: "It's a race, not a sprint, and the pace is patience. Slow and still-going beats fast and quit." },
      { t: 'For whom the Lord loveth he chasteneth.', r: 'Hebrews 12:6',
        w: "The correction you resent isn't proof He's against you. It's proof you're His." },
      { t: 'That the trial of your faith, being much more precious than of gold that perisheth, though it be tried with fire.', r: '1 Peter 1:7',
        w: "The fire isn't punishment. It's the assay. What survives it is worth more than gold." },
      { t: 'But the God of all grace, after that ye have suffered a while, make you perfect, stablish, strengthen, settle you.', r: '1 Peter 5:10',
        w: "'A while,' not forever. And look what's on the other side: established, strengthened, settled." },
      { t: 'For our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory.', r: '2 Corinthians 4:17',
        w: "Weigh it honestly: a moment of affliction against an eternal weight of glory. The math favors you." },
      { t: 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.', r: 'Romans 8:28',
        w: "Not all things are good. But all things work together — and He's the one running the assembly." },
      { t: 'Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.', r: 'Proverbs 3:5-6',
        w: "Your own understanding is exactly what's exhausted right now. Lean somewhere stronger." },
      { t: 'My son, despise not the chastening of the LORD; neither be weary of his correction.', r: 'Proverbs 3:11',
        w: "Don't waste the correction by resenting it. The lesson costs less the first time it's offered." },
      { t: 'Be not deceived; God is not mocked: for whatsoever a man soweth, that shall he also reap.', r: 'Galatians 6:7',
        w: "The seeds you're planting in private become the harvest you'll stand in publicly. Plant accordingly." },
      { t: 'If any man will come after me, let him deny himself, and take up his cross daily, and follow me.', r: 'Luke 9:23',
        w: "Daily. Not in one heroic burst — in the unglamorous repeat. That's where it's actually decided." },
      { t: 'Know ye not that they which run in a race run all, but one receiveth the prize? So run, that ye may obtain.', r: '1 Corinthians 9:24',
        w: "Showing up isn't the same as running to win. Run like the prize is real — because it is." },
      { t: 'But I keep under my body, and bring it into subjection.', r: '1 Corinthians 9:27',
        w: "Your feelings make a terrible boss. Somebody has to be in charge in there — make it you." },
      { t: 'Thou therefore endure hardness, as a good soldier of Jesus Christ.', r: '2 Timothy 2:3',
        w: "Hardness isn't a sign you're off course. Soldiers expect it. Endure it like one." },
      { t: 'I have fought a good fight, I have finished my course, I have kept the faith.', r: '2 Timothy 4:7',
        w: "That's the line you want to say at the end. You write it now, one kept-going day at a time." },
      { t: 'But he knoweth the way that I take: when he hath tried me, I shall come forth as gold.', r: 'Job 23:10',
        w: "He knows the way you're taking even when you don't. You don't come out of this burned — you come out gold." },
      { t: 'It is good for me that I have been afflicted; that I might learn thy statutes.', r: 'Psalm 119:71',
        w: "One day you'll say the affliction was good — not because it was fun, but because of who it taught you to be." },
      { t: 'Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.', r: 'Proverbs 27:17',
        w: "Sharpening involves friction and sparks. If it's grinding on you, it might be working." },
      { t: 'Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit.', r: 'Ecclesiastes 7:8',
        w: "Anyone can start hot. The end is what counts — and patience, not pride, is what gets you there." },
      { t: 'Rejoicing in hope; patient in tribulation; continuing instant in prayer.', r: 'Romans 12:12',
        w: "Three jobs for the hard season: hope, patience, prayer. Do those three and you'll outlast it." },
      { t: 'Behold, I have refined thee, but not with silver; I have chosen thee in the furnace of affliction.', r: 'Isaiah 48:10',
        w: "You weren't forgotten in the furnace. You were chosen there. The heat is part of being picked." },
      { t: 'Because strait is the gate, and narrow is the way, which leadeth unto life, and few there be that find it.', r: 'Matthew 7:14',
        w: "If the road feels narrow and lonely, you might be on the right one. Easy and crowded leads elsewhere." },
    ],
  },
};

// Deterministic "verse of the day": stable for the whole day, rolls over at LOCAL midnight.
// Uses the local calendar date (not UTC) so the verse changes at the user's midnight,
// not at UTC midnight (which is mid-day in NZ/AU).
export function dailyIndex(len, offset = 0) {
  const now = new Date();
  const local = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const day = Math.round(local.getTime() / 864e5);
  return (((day + offset) % len) + len) % len;
}
